# Generated by Django 3.2.5 on 2021-07-11 19:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210711_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, default=uuid.uuid4, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_receipt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 22, 16, 33, 510673)),
        ),
    ]
