# Generated by Django 3.2.5 on 2021-07-11 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210711_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='er', max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_receipt',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 22, 21, 35, 764918)),
        ),
    ]
