# Generated by Django 3.2.5 on 2021-07-14 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210711_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_receipt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('header', models.CharField(max_length=60)),
                ('text', models.TextField(max_length=10000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
