# Generated by Django 3.2.5 on 2021-07-14 18:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210714_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(default=uuid.uuid4, max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
