# Generated by Django 3.2.5 on 2021-07-15 15:41

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20210714_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='', upload_to=patients.models.Patient.generate_user_path),
            preserve_default=False,
        ),
    ]
