# Generated by Django 3.2.5 on 2021-07-15 15:59

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to=patients.models.Patient.generate_user_path),
        ),
    ]
