# Generated by Django 3.2.5 on 2021-07-15 16:05

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=patients.models.Patient.generate_user_path),
        ),
    ]
